/* eslint-disable */
require('./arrow-alt-circle-left')
require('./bars')
require('./bullhorn')
require('./download')
require('./envelope')
require('./git')
require('./github')
require('./js')
require('./laravel')
require('./linkedin-in')
require('./map-marker-alt')
require('./php')
require('./sass')
require('./sketch')
require('./twitter')
require('./vuejs')
